name: test-config

# https://developer.ebay.com/DevZone/SandboxUser/
# Register a sandbox test user and use that Credentials here
#sandbox-user:
#    username: achekeev88@gmail.com
#    password: 147852zxc@
sandbox-user:
    username: dakt.kg@gmail.com
    password: liderkgz312!

# Register a production test user and use that Credentials here - https://reg.ebay.com/reg/PartialReg
production-user:
    username: dakt.kg@gmail.com
    password: liderkgz312!